apiVersion: v1
kind: Service
metadata:
  name: mts-notification-ndport
spec:
  type: NodePort
  selector:
    app: mts-notification
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      nodePort: 30010